apiVersion: apps/v1
kind: Deployment
metadata:
  name: axfr-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axfr-backend
  template:
    metadata:
      labels:
        app: axfr-backend
    spec:
      initContainers:
        - name: init-wait
          image: alpine:3.17
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 mariadb-service 3306 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name: axfr
          image: dockr.it/goaxfrbackend:k8s
          imagePullPolicy: Always
          env:
          - name: MYSQL_HOSTNAME
            value: mariadb-service
          - name: MYSQL_SE_DATABASE
            value: sediff
          - name: MYSQL_SE_USERNAME
            value: sediff
          - name: MYSQL_SE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: axfrsemysqlpassword 
                key: password
          - name: MYSQL_SEDUMP_DATABASE
            value: sedump
          - name: MYSQL_SEDUMP_USERNAME
            value: sedump
          - name: MYSQL_SEDUMP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: axfrsedumpmysqlpassword 
                key: password
          - name: MYSQL_NU_DATABASE
            value: nudiff
          - name: MYSQL_NU_USERNAME
            value: nudiff
          - name: MYSQL_NU_PASSWORD
            valueFrom:
              secretKeyRef:
                name: axfrnumysqlpassword 
                key: password
          - name: MYSQL_NUDUMP_DATABASE
            value: nudump
          - name: MYSQL_NUDUMP_USERNAME
            value: nudump
          - name: MYSQL_NUDUMP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: axfrnudumpmysqlpassword 
                key: password
          - name: AUTHHEADER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: axfrbackendauthheaderpassword
                key: password
          - name: CORS_HEADER
            value: https://axfr.se
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockrit
